services:
  postgres:
    image: timescale/timescaledb-ha:pg18-all-arm64
    container_name: poly-asian
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TIMESCALEDB_TELEMETRY_DISABLED=${TIMESCALEDB_TELEMETRY_DISABLED}
    ports:
      - "5432:5432"
    volumes:
      - polyasian_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - poly-asian-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 10s
      retries: 10

networks:
  poly-asian-network:
    name: poly-asian-network
    driver: bridge

volumes:
  polyasian_data:
