CREATE TABLE IF NOT EXISTS hot_events (
    time TIMESTAMPTZ NOT NULL,
    id TEXT NOT NULL,
    ticker TEXT,
    slug TEXT,
    title TEXT,
    subtitle TEXT,
    description TEXT,
    resolution_source TEXT,
    start_date TIMESTAMPTZ,
    creation_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    image TEXT,
    icon TEXT,
    active BOOLEAN,
    closed BOOLEAN,
    archived BOOLEAN,
    new BOOLEAN,
    featured BOOLEAN,
    restricted BOOLEAN,
    liquidity NUMERIC,
    volume NUMERIC,
    open_interest NUMERIC,
    sort_by TEXT,
    category TEXT,
    subcategory TEXT,
    is_template BOOLEAN,
    template_variables TEXT,
    published_at TEXT,
    created_by TEXT,
    updated_by TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    comments_enabled BOOLEAN,
    competitive NUMERIC,
    volume_24hr NUMERIC,
    volume_1wk NUMERIC,
    volume_1mo NUMERIC,
    volume_1yr NUMERIC,
    featured_image TEXT,
    disqus_thread TEXT,
    parent_event TEXT,
    enable_order_book BOOLEAN,
    liquidity_amm NUMERIC,
    liquidity_clob NUMERIC,
    neg_risk BOOLEAN,
    neg_risk_market_id TEXT,
    neg_risk_fee_bips INTEGER,
    comment_count INTEGER,
    cyom BOOLEAN,
    tags JSONB,
    sub_events TEXT[],
    PRIMARY KEY (time, id)
);

-- Convert to hypertable partitioned by time
SELECT create_hypertable('hot_events', 'time', if_not_exists => TRUE);

-- Index for querying by category and recency
CREATE INDEX IF NOT EXISTS idx_hot_events_category ON hot_events (category, time DESC);
CREATE INDEX IF NOT EXISTS idx_hot_events_volume_24hr ON hot_events (volume_24hr DESC, time DESC);
